# Generated by Django 4.2.2 on 2023-07-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=127)),
                ('city', models.CharField(max_length=127)),
                ('number', models.IntegerField()),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
