# Generated by Django 4.2.2 on 2023-07-12 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_vouchers',
            field=models.CharField(choices=[('10% OFF', 'Off10'), ('25% OFF', 'Off25'), ('80% OFF', 'Off80')], default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
